project:
  type: website
  output-dir: docs
  resources: 
    - "figures"

website:
  title: "NycTaxi"
  navbar:
    logo: figures/nyc-taxi-navbar-logo.png
    logo-alt: "Project logo."
    title: false
    collapse-below: lg
    left:
      - text: Home
        href: index.qmd
      - text: "Project Phases"
        menu:
          - text: "01 - Business Understanding Overview"
            href: investigation-phases/01-business-understanding.qmd   
          - text: "02 - Defining Development Environment"
            href: investigation-phases/02-defining-environment.qmd
          - text: "03 - Data Collection Process"
            href: investigation-phases/03-data-collection-process.qmd         
          - text: "04 - Defining Base Line"
            href: investigation-phases/04-base-line.qmd   
          - text: "05 - Data Sampling"
            href: investigation-phases/05-data-sampling.qmd
          - text: "06 - Initial Exploration"
            href: investigation-phases/06-initial-exploration.qmd 
          - text: "07 - Expanding Geospatial Information"
            href: investigation-phases/07-expanding-geospatial-data.qmd
          - text: "08 - Exploring Transportation and Socioeconomic Patterns"
            href: investigation-phases/08-expanding-transportation-socioeconomic.qmd
          - text: "09 - Training Initial models"
            href: investigation-phases/09-training-initial-models.qmd
          - text: "10 - Explaining Top Models"
            href: investigation-phases/10-explaining-top-models.qmd        
    right:
      - text: "About Angel Feliz"
        href: about.qmd
      - icon: github
        href: https://github.com/AngelFelizR/
      - icon: linkedin
        href: https://do.linkedin.com/in/angel-esteban-feliz-ferreras

format:
  html:
    theme: cosmo
    toc: true

editor: source