# This file was generated by the {rix} R package v0.16.0 on 2025-09-22
# with following call:
# >rix(r_ver = "f7dc05ba7d46f98f98b7c08b63c50f2f05b0e5c7",
#  > r_pkgs = c("data.table",
#  > "lubridate",
#  > "stringr",
#  > "tibble",
#  > "timeDate",
#  > "fst",
#  > "qs2",
#  > "rvest",
#  > "here",
#  > "osmdata",
#  > "tidycensus",
#  > "units",
#  > "leaflet",
#  > "maptiles",
#  > "sf",
#  > "tmap",
#  > "tidymodels",
#  > "baguette",
#  > "rules",
#  > "corrr",
#  > "mixOmics",
#  > "glmnet",
#  > "kernlab",
#  > "ranger",
#  > "xgboost",
#  > "DBI",
#  > "duckdb",
#  > "tidytext",
#  > "stringdist",
#  > "hashr",
#  > "igraph",
#  > "glue",
#  > "withr",
#  > "ggplot2",
#  > "scales",
#  > "ggiraph",
#  > "DiagrammeR",
#  > "patchwork",
#  > "gt",
#  > "infer",
#  > "recipes",
#  > "future",
#  >      "future.apply",
#  > "tictoc",
#  > "knitr",
#  > "rmarkdown",
#  > "devtools",
#  > "testthat"),
#  > system_pkgs = c("quarto"),
#  > git_pkgs = list(package_name = "corrcat",
#  > repo_url = "https://github.com/AngelFelizR/corrcat/",
#  > commit = "d20b6ad6a01d3b5a605037dbffbca3a18e97ac00"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses upstream nixpkgs' revision f7dc05ba7d46f98f98b7c08b63c50f2f05b0e5c7 for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/f7dc05ba7d46f98f98b7c08b63c50f2f05b0e5c7.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      baguette
      corrr
      data_table
      DBI
      devtools
      DiagrammeR
      duckdb
      fst
      future
      future_apply
      ggiraph
      ggplot2
      glmnet
      glue
      gt
      hashr
      here
      igraph
      infer
      kernlab
      knitr
      leaflet
      lubridate
      maptiles
      mixOmics
      osmdata
      patchwork
      qs2
      ranger
      recipes
      rmarkdown
      rules
      rvest
      scales
      sf
      stringdist
      stringr
      testthat
      tibble
      tictoc
      tidycensus
      tidymodels
      tidytext
      timeDate
      tmap
      units
      withr
      xgboost;
  };
 
    corrcat = (pkgs.rPackages.buildRPackage {
      name = "corrcat";
      src = pkgs.fetchgit {
        url = "https://github.com/AngelFelizR/corrcat/";
        rev = "d20b6ad6a01d3b5a605037dbffbca3a18e97ac00";
        sha256 = "sha256-MT+SEkz/6VRIc9JairTCt0gEmxLGpgPH4eevlFqPUyA=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          data_table
          rcompanion
          tibble;
      };
    });
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ corrcat rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
