# This file was generated by the {rix} R package v0.16.0 on 2025-09-14
# with following call:
# >rix(r_ver = "e27a1a7251205d1d6404fac671b5f86192dde175",
#  > r_pkgs = c("data.table",
#  > "lubridate",
#  > "stringr",
#  > "tibble",
#  > "timeDate",
#  > "fst",
#  > "qs2",
#  > "rvest",
#  > "here",
#  > "osmdata",
#  > "tidycensus",
#  > "units",
#  > "leaflet",
#  > "maptiles",
#  > "sf",
#  > "tmap",
#  > "tidymodels",
#  > "baguette",
#  > "rules",
#  > "corrr",
#  > "mixOmics",
#  > "glmnet",
#  > "kernlab",
#  > "ranger",
#  > "xgboost",
#  > "DBI",
#  > "duckdb",
#  > "tidytext",
#  > "stringdist",
#  > "hashr",
#  > "igraph",
#  > "glue",
#  > "withr",
#  > "ggplot2",
#  > "scales",
#  > "ggiraph",
#  > "DiagrammeR",
#  > "patchwork",
#  > "gt",
#  > "infer",
#  > "recipes",
#  > "future",
#  >      "future.apply",
#  > "tictoc",
#  > "knitr",
#  > "rmarkdown",
#  > "devtools",
#  > "testthat"),
#  > system_pkgs = c("quarto",
#  > "git"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses upstream nixpkgs' revision e27a1a7251205d1d6404fac671b5f86192dde175 for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/e27a1a7251205d1d6404fac671b5f86192dde175.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      baguette
      corrr
      data_table
      DBI
      devtools
      DiagrammeR
      duckdb
      fst
      future
      future_apply
      ggiraph
      ggplot2
      glmnet
      glue
      gt
      hashr
      here
      igraph
      infer
      kernlab
      knitr
      leaflet
      lubridate
      maptiles
      mixOmics
      osmdata
      patchwork
      qs2
      ranger
      recipes
      rmarkdown
      rules
      rvest
      scales
      sf
      stringdist
      stringr
      testthat
      tibble
      tictoc
      tidycensus
      tidymodels
      tidytext
      timeDate
      tmap
      units
      withr
      xgboost;
  };
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      nix
      quarto
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [  rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
