---
title: "Feature selection"
editor_options: 
  chunk_output_type: console
execute:
  message: false
  warning: false
---


## Setting up the environment

### Loading libraries

```{r}
## To manage relative paths
library(here)

## To transform data that fits in RAM
library(lubridate)
library(timeDate)
library(ggtext)

## Tools for modeling
library(tidymodels)
library(themis)

## Tools for intepreting ML
library(DALEX)

## Publish data sets, models, and other R objects
library(pins)

## Custom functions
devtools::load_all()

# Defining the pin boards to use
BoardLocal <- board_folder(here("../NycTaxiPins/Board"))

# Loading params
Params <- yaml::read_yaml(here("params.yml"))
Params$BoroughColors <- unlist(Params$BoroughColors)
```

### Importing training data

Here we import the data to use from the remote Board located in a github repo.

```{r}
#| eval: false

AcsVariablesByZoneId <- pin_read(BoardLocal, "AcsVariablesByZoneId")[,
  LocationID := as.character(LocationID)
]

OmsDensityFeatures <- pin_read(BoardLocal, "OmsDensityFeatures")[,
  LocationID := as.character(LocationID)
]

ZoneCodesRef <- pin_read(BoardLocal, "ZoneCodesRef")[, c(
  "LocationID",
  "Borough",
  "service_zone"
)]

ConsolidationRecipe <- pin_read(
  BoardLocal,
  "ConsolidationRecipe"
)

SampledData <-
  pin_list(BoardLocal) |>
  grep(pattern = "^OneMonthData", value = TRUE) |>
  sort() |>
  head(12L) |>
  lapply(FUN = pin_read, board = BoardLocal) |>
  rbindlist() |>
  tibble::as_tibble() |>
  mutate(
    take_current_trip = fifelse(take_current_trip == 1L, "yes", "no") |>
      factor(levels = c("yes", "no")),
    PULocationID = as.character(PULocationID),
    DOLocationID = as.character(DOLocationID)
  )

set.seed(2545)
TrainingSample <-
  initial_split(SampledData, strata = take_current_trip) |>
  training()

ConsolidationRecipe <- pin_read(
  BoardLocal,
  "ConsolidationRecipe"
)

set.seed(2971)
TrainingCompleteSplit <-
  prep(ConsolidationRecipe) |>
  bake(new_data = TrainingSample) |>
  initial_split(strata = take_current_trip)

TrainingCompleteTraining <- training(TrainingCompleteSplit)
TrainingCompleteTesting <- testing(TrainingCompleteSplit)
```

### Fitting workflows
    
```{r}
InitialLogisticWf <- pin_read(
  BoardLocal,
  "InitialLogisticWf"
)

InitialRandomForestWf <- pin_read(
  BoardLocal,
  "InitialRandomForestWf"
)

InitialLogisticWfFitted <- fit(
  InitialLogisticWf,
  data = TrainingCompleteTraining
)

InitialRandomForestWfFitted <- fit(
  InitialRandomForestWf,
  data = TrainingCompleteTraining
)

pin_write(
  BoardLocal,
  InitialLogisticWfFitted,
  "InitialLogisticWfFitted",
  type = "qs2",
  title = "Initial Logistic Wf Fitted"
)

pin_write(
  BoardLocal,
  InitialRandomForestWfFitted,
  "InitialRandomForestWfFitted",
  type = "qs2",
  title = "Initial Random Forest Wf Fitted"
)
```

```{r}
InitialLogisticWfFitted <- pin_read(
  BoardLocal,
  "InitialLogisticWfFitted"
)

InitialRandomForestWfFitted <- pin_read(
  BoardLocal,
  "InitialRandomForestWfFitted"
)
```


## Creating explainers

```{r}
ExplainerLogistic <- DALEXtra::explain_tidymodels(
  InitialLogisticWfFitted,
  data = TrainingCompleteTesting |> select(-take_current_trip),
  y = TrainingCompleteTesting$take_current_trip
)

ExplainerRandomForest <- DALEXtra::explain_tidymodels(
  InitialRandomForestWfFitted,
  data = TrainingCompleteTesting |> select(-take_current_trip),
  y = TrainingCompleteTesting$take_current_trip
)

pin_write(
  BoardLocal,
  ExplainerLogistic,
  "ExplainerLogistic",
  type = "qs2",
  title = "Explainer Logistic"
)

pin_write(
  BoardLocal,
  ExplainerRandomForest,
  "ExplainerRandomForest",
  type = "qs2",
  title = "Explainer Random Forest"
)
```

## Getting VIP

```{r}
brier_class_dalex <- get_loss_yardstick(
  brier_class,
  reverse = FALSE,
  reference = 1
)

set.seed(1980)
ExplainerLogisticVip <- model_parts(
  explainer = ExplainerLogistic,
  loss_function = brier_class_dalex,
  B = 50,
  type = "difference"
)

set.seed(1850)
ExplainerRandomForestVip <- model_parts(
  explainer = ExplainerRandomForest,
  loss_function = brier_class_dalex,
  B = 50,
  type = "difference"
)

pin_write(
  BoardLocal,
  ExplainerLogisticVip,
  "ExplainerLogisticVip",
  type = "qs2",
  title = "Explainer Logistic Vip"
)

pin_write(
  BoardLocal,
  ExplainerRandomForestVip,
  "ExplainerRandomForestVip",
  type = "qs2",
  title = "Explainer Random Forest Vip"
)
```


```{r}
ExplainerLogisticVip |>
  as.data.frame() |>
  group_by(variable) |>
  summarize(dropout_loss = mean(dropout_loss)) |>
  arrange(desc(dropout_loss)) |>
  (\(x) bind_rows(head(x, 10L), tail(x, 10L)))()
```

```{r}
ExplainerRandomForestVip |>
  as.data.frame() |>
  group_by(variable) |>
  summarize(dropout_loss = mean(dropout_loss)) |>
  arrange(desc(dropout_loss)) |>
  (\(x) bind_rows(head(x, 10L), tail(x, 10L)))()
```