---
title: "Investigating Model Disagreements: Instance-Level Model Analysis"
editor_options: 
  chunk_output_type: console
execute:
  message: false
  warning: false
---


## Setting up the environment

### Loading libraries

```{r}
## To manage relative paths
library(here)

## To transform data that fits in RAM
library(timeDate)
library(ggtext)

## Tools for modeling
library(tidymodels)
library(themis)

## Tools for intepreting ML
library(DALEX)

## Publish data sets, models, and other R objects
library(pins)

## Custom functions
devtools::load_all()

# Defining the pin boards to use
BoardLocal <- board_folder(here("../NycTaxiPins/Board"))

# Loading params
Params <- yaml::read_yaml(here("params.yml"))
Params$BoroughColors <- unlist(Params$BoroughColors)
```

### Importing training data

Here we import the data to use from the remote Board located in a github repo.

```{r}
#| eval: false

AcsVariablesByZoneId <- pin_read(BoardLocal, "AcsVariablesByZoneId")[,
  LocationID := as.character(LocationID)
]

OmsDensityFeatures <- pin_read(BoardLocal, "OmsDensityFeatures")[,
  LocationID := as.character(LocationID)
]

ZoneCodesRef <- pin_read(BoardLocal, "ZoneCodesRef")[, c(
  "LocationID",
  "Borough",
  "service_zone"
)]

ConsolidationRecipe <- pin_read(
  BoardLocal,
  "ConsolidationRecipe"
)

SampledData <-
  pin_list(BoardLocal) |>
  grep(pattern = "^OneMonthData", value = TRUE) |>
  sort() |>
  head(12L) |>
  lapply(FUN = pin_read, board = BoardLocal) |>
  rbindlist() |>
  tibble::as_tibble() |>
  mutate(
    take_current_trip = fifelse(take_current_trip == 1L, "yes", "no") |>
      factor(levels = c("yes", "no")),
    PULocationID = as.character(PULocationID),
    DOLocationID = as.character(DOLocationID)
  )

set.seed(2545)
TrainingSample <-
  initial_split(SampledData, strata = take_current_trip) |>
  training()

set.seed(2971)
ExplainSplit <- initial_split(TrainingSample, strata = take_current_trip)


ExplainTraining <-
  prep(ConsolidationRecipe) |>
  bake(new_data = training(ExplainSplit))

ExplainTesting <-
  prep(ConsolidationRecipe) |>
  bake(new_data = testing(ExplainSplit))

pin_write(
  BoardLocal,
  ExplainTraining,
  "ExplainTraining",
  type = "qs2",
  title = "Explain Training"
)

pin_write(
  BoardLocal,
  ExplainTesting,
  "ExplainTesting",
  type = "qs2",
  title = "Explain Testing"
)
```

```{r}
#| echo: false

ExplainTraining <- pin_read(
  BoardLocal,
  "ExplainTraining"
)

ExplainTesting <- pin_read(
  BoardLocal,
  "ExplainTesting"
)
```

### Importing workflows to train

```{r}

InitialLogisticWf <- pin_read(
  BoardLocal,
  "InitialLogisticWf"
)

InitialRandomForestWf <- pin_read(
  BoardLocal,
  "InitialRandomForestWf"
)
```

## Fitting model

```{r}
#| eval: false

InitialLogisticWfFitted <- fit(
  InitialLogisticWf,
  data = ExplainTraining
)

InitialRandomForestWfFitted <- fit(
  InitialRandomForestWf,
  data = ExplainTraining
)

pin_write(
  BoardLocal,
  InitialLogisticWfFitted,
  "InitialLogisticWfFitted",
  type = "qs2",
  title = "Initial Logistic Wf Fitted"
)

pin_write(
  BoardLocal,
  InitialRandomForestWfFitted,
  "InitialRandomForestWfFitted",
  type = "qs2",
  title = "Initial Random Forest Wf Fitted"
)
```

```{r}
#| echo: false

InitialLogisticWfFitted <- pin_read(
  BoardLocal,
  "InitialLogisticWfFitted"
)

InitialRandomForestWfFitted <- pin_read(
  BoardLocal,
  "InitialRandomForestWfFitted"
)
```


```{r}
#| eval: false

TrainedModels <- list(
  "logistic" = InitialLogisticWfFitted,
  "ramdom_forest" = InitialRandomForestWfFitted
)

TrainedModelPreds <-
  lapply(names(TrainedModels), \(x) {
    predict(TrainedModels[[x]], new_data = ExplainTesting) |>
      add_rowindex() |>
      mutate(.pred_class = as.character(.pred_class), model_name = x) |>
      bind_cols(
        predict(TrainedModels[[x]], new_data = ExplainTesting, type = "prob"),
      )
  }) |>
  bind_rows() |>
  pivot_wider(
    id_cols = .row,
    names_from = model_name,
    values_from = c(.pred_class, .pred_no)
  )

ExamplesToImproveLogistic <-
  ExplainTesting |>
  mutate(
    take_current_trip = as.character(take_current_trip),
    no_prob = if_else(take_current_trip == "no", 1L, 0L)
  ) |>
  add_rowindex() |>
  left_join(TrainedModelPreds, by = ".row") |>
  filter(
    .pred_class_logistic != .pred_class_ramdom_forest,
    take_current_trip == .pred_class_ramdom_forest
  ) |>
  mutate(logistic_residuals = no_prob - .pred_no_logistic) |>
  arrange(desc(abs(logistic_residuals)))

pin_write(
  BoardLocal,
  ExamplesToImproveLogistic,
  "ExamplesToImproveLogistic",
  type = "qs2",
  title = "Examples To Improve Logistic"
)
```

```{r}
#| echo: false

ExamplesToImproveLogistic <- pin_read(
  BoardLocal,
  "ExamplesToImproveLogistic"
)
```

## Creating explainers

```{r}
ExplainerLogistic <- DALEXtra::explain_tidymodels(
  InitialLogisticWfFitted,
  data = ExplainTesting |> select(-take_current_trip),
  y = ExplainTesting$take_current_trip == "no"
)

ExplainerRandomForest <- DALEXtra::explain_tidymodels(
  InitialRandomForestWfFitted,
  data = ExplainTesting |> select(-take_current_trip),
  y = ExplainTesting$take_current_trip == "no"
)
```


```{r}
#| eval: false

top_logic <-
  ExamplesToImproveLogistic |>
  slice_head(n = 1L) |>
  predict_parts(
    explainer = ExplainerLogistic,
    type = "break_down"
  )

top_rf <-
  ExamplesToImproveLogistic |>
  slice_head(n = 1L) |>
  predict_parts(
    explainer = ExplainerRandomForest,
    type = "break_down_interactions"
  )

pin_write(
  BoardLocal,
  top_logic,
  "top_logic",
  type = "qs2",
  title = "top_logic"
)

pin_write(
  BoardLocal,
  top_rf,
  "top_rf",
  type = "qs2",
  title = "top_rf"
)
```

```{r}
#| echo: false
top_logic <- pin_read(
  BoardLocal,
  "top_logic"
)
```

```{r}
ExamplesToImproveLogistic |>
  slice_head(n = 1) |>
  predict(object = InitialLogisticWfFitted, type = "prob")

ExamplesToImproveLogistic |>
  slice_head(n = 1) |>
  select(
    trip_id,
    trip_time,
    driver_pay,
    take_current_trip,
    .pred_no_logistic,
    .pred_no_ramdom_forest
  )

plot(top_logic)
```

```{r}
extract_fit_parsnip(InitialLogisticWfFitted) |>
  broom::tidy() |>
  select(term, estimate) |>
  arrange(desc(abs(estimate))) |>
  slice_head(n = 15)
```

```{r}

```

```{r}

plot(top_rf)
```




